research_task:
  description: >
    Conduct a thorough market research about {topic} using the tools provided to you
    Make sure you find interesting and relevant information given
    the current year is {current_year}.
  expected_output: >
    A list with 10 detailed bullet points of the most relevant information about {topic}
  agent: senior_market_researcher

reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledged report with the main topics, each with a full section of information.
    Formatted as markdown without '```'
  agent: reporting_analyst
  output_file: output/report.md

copywriting_task:
  description: >
    Create a blog post about {topic} that is engaging and informative and make people want to take action to buy.
  expected_output: >
    A well-written blog post that captures the essence of {topic} and provides value to the reader and makes them want to take action.
    Formatted as markdown without '```'
  agent: copywriter
  context: [research_task, reporting_task]
  output_file: output/copywriting_blog_post.md